import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT


def generate_approval_certificate(submission_id: str, form_data: dict, ai_result: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                            leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Header
    header_style = ParagraphStyle('header', fontSize=22, alignment=TA_CENTER,
                                   textColor=colors.HexColor('#1B4332'), fontName='Helvetica-Bold',
                                   spaceAfter=6)
    sub_style = ParagraphStyle('sub', fontSize=12, alignment=TA_CENTER,
                                textColor=colors.HexColor('#555555'), spaceAfter=4)
    body_style = ParagraphStyle('body', fontSize=10, spaceAfter=4)

    story.append(Paragraph("DUBAI CIVIL DEFENCE", header_style))
    story.append(Paragraph("Building Plan Compliance Certificate", sub_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#1B4332')))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("✓ APPROVED", ParagraphStyle('approved', fontSize=28,
                            alignment=TA_CENTER, textColor=colors.HexColor('#1B4332'),
                            fontName='Helvetica-Bold', spaceAfter=8)))
    story.append(Spacer(1, 0.3*cm))

    # Reference and date
    ref_num = f"DCD-{datetime.now(timezone.utc).year}-{submission_id[-5:].upper()}"
    table_data = [
        ["Reference Number:", ref_num],
        ["Issue Date:", datetime.now(timezone.utc).strftime("%d %B %Y")],
        ["Submission Type:", form_data.get("submission_type", "N/A").replace("_", " ").title()],
        ["Project / Property:", form_data.get("project_name") or form_data.get("shop_name", "N/A")],
        ["Applicant:", form_data.get("applicant_name", "N/A")],
        ["AI Confidence Score:", f"{ai_result.get('confidence', 0)}%"],
        ["Checks Passed:", f"{ai_result.get('pass_count', 0)} / 10"],
    ]
    t = Table(table_data, colWidths=[5*cm, 12*cm])
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#F0FFF4'), colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CCCCCC')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    # Summary
    story.append(Paragraph("AI Review Summary", ParagraphStyle('h2', fontSize=12,
                            fontName='Helvetica-Bold', spaceAfter=4)))
    story.append(Paragraph(ai_result.get("summary", ""), body_style))
    story.append(Spacer(1, 0.3*cm))

    # Checklist
    story.append(Paragraph("Compliance Checklist", ParagraphStyle('h2', fontSize=12,
                            fontName='Helvetica-Bold', spaceAfter=4)))
    check_data = [["Rule", "Result", "Value"]]
    for check in ai_result.get("checks", []):
        result_text = "PASS ✓" if check["passed"] else ("N/A" if not check.get("verifiable", True) else "FAIL ✗")
        check_data.append([check["name"], result_text, check.get("extracted_value", "-")])

    ct = Table(check_data, colWidths=[7*cm, 3*cm, 7*cm])
    ct.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1B4332')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CCCCCC')),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F9F9F9')]),
    ]))
    story.append(ct)
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#CCCCCC')))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        "This certificate is generated by the CivGuard AI system and is subject to verification by a "
        "DCD officer. This document does not constitute final approval until verified.",
        ParagraphStyle('footer', fontSize=8, textColor=colors.HexColor('#888888'), alignment=TA_CENTER)
    ))

    doc.build(story)
    return buffer.getvalue()


def generate_rejection_report(submission_id: str, form_data: dict, ai_result: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                            leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    header_style = ParagraphStyle('header', fontSize=22, alignment=TA_CENTER,
                                   textColor=colors.HexColor('#7F1D1D'), fontName='Helvetica-Bold',
                                   spaceAfter=6)
    sub_style = ParagraphStyle('sub', fontSize=12, alignment=TA_CENTER,
                                textColor=colors.HexColor('#555555'), spaceAfter=4)
    body_style = ParagraphStyle('body', fontSize=10, spaceAfter=4)

    story.append(Paragraph("DUBAI CIVIL DEFENCE", header_style))
    story.append(Paragraph("Building Plan Review – Correction Required", sub_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#7F1D1D')))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("✗ CORRECTIONS REQUIRED", ParagraphStyle('rejected', fontSize=24,
                            alignment=TA_CENTER, textColor=colors.HexColor('#7F1D1D'),
                            fontName='Helvetica-Bold', spaceAfter=8)))
    story.append(Spacer(1, 0.3*cm))

    ref_num = f"DCD-{datetime.now(timezone.utc).year}-{submission_id[-5:].upper()}"
    table_data = [
        ["Reference Number:", ref_num],
        ["Report Date:", datetime.now(timezone.utc).strftime("%d %B %Y")],
        ["Project / Property:", form_data.get("project_name") or form_data.get("shop_name", "N/A")],
        ["Critical Failures:", str(ai_result.get("critical_failures", 0))],
        ["Total Failures:", str(ai_result.get("fail_count", 0))],
    ]
    t = Table(table_data, colWidths=[5*cm, 12*cm])
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CCCCCC')),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#FFF5F5'), colors.white]),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    story.append(Paragraph("AI Review Summary", ParagraphStyle('h2', fontSize=12,
                            fontName='Helvetica-Bold', spaceAfter=4)))
    story.append(Paragraph(ai_result.get("summary", ""), body_style))
    story.append(Spacer(1, 0.3*cm))

    # Failed checks
    failed = [c for c in ai_result.get("checks", []) if not c["passed"] and c.get("verifiable", True)]
    if failed:
        story.append(Paragraph("Items Requiring Correction", ParagraphStyle('h2', fontSize=12,
                                fontName='Helvetica-Bold', spaceAfter=4)))
        for i, check in enumerate(failed, 1):
            story.append(Paragraph(f"{i}. {check['name']} [{check['severity']}]",
                                    ParagraphStyle('item_h', fontSize=10, fontName='Helvetica-Bold',
                                                   textColor=colors.HexColor('#7F1D1D'), spaceAfter=2)))
            story.append(Paragraph(f"Found: {check.get('extracted_value', 'N/A')} | Required: {check.get('required_value', 'N/A')}",
                                    ParagraphStyle('item_v', fontSize=9, leftIndent=12, spaceAfter=2)))
            if check.get("notes"):
                story.append(Paragraph(check["notes"], ParagraphStyle('item_n', fontSize=9,
                                                                        leftIndent=12, textColor=colors.HexColor('#555555'), spaceAfter=6)))

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#CCCCCC')))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        "Please address all CRITICAL items before resubmitting. ADVISORY items are recommended corrections.",
        ParagraphStyle('footer', fontSize=8, textColor=colors.HexColor('#888888'), alignment=TA_CENTER)
    ))

    doc.build(story)
    return buffer.getvalue()
