DCD_RULES = {
    'exit_width_min_mm': 900,
    'exit_count_min': 2,
    'exit_separation_sprinklered_fraction': 1/3,
    'exit_separation_nonsprinklered_fraction': 1/2,
    'travel_distance_sprinklered_max_m': 60,
    'travel_distance_nonsprinklered_max_m': 45,
    'corridor_width_min_mm': 1200,
    'staircase_width_min_mm': 1200,
    'dead_end_max_m': 6,
    'sprinkler_required_floors': 3,
    'sprinkler_required_height_m': 14,
    'sprinkler_coverage_ordinary_hazard_max_m2': 12.4,
    'sprinkler_coverage_light_hazard_max_m2': 20.9,
    'smoke_detector_max_coverage_m2': 60,
    'smoke_detector_max_spacing_m': 7.5,
    'heat_detector_max_coverage_m2': 30,
    'extinguisher_max_travel_m': 25,
    'extinguisher_per_area_m2': 200,
    'fire_hose_max_reach_m': 30,
    'manual_call_point_max_travel_m': 30,
    'fire_truck_access_min_width_m': 4,
    'fire_truck_overhead_clearance_m': 4,
    'hydrant_max_distance_m': 100,
    'assembly_point_min_distance_m': 20,
    'fire_compartment_max_area_m2': 2000,
    'wet_riser_min_floors': 7,
    'dry_riser_min_floors': 4,
    'refuge_floor_required_height_m': 75,
    'emergency_lighting_battery_min_hours': 1,
    'emergency_lighting_min_lux': 1,
}

RULE_METADATA = {
    'exit_width': {
        'name': 'Emergency Exit Width',
        'description': 'Minimum 900 mm clear width per exit door.',
        'reference': 'Chapter 10 – Means of Egress, Section 11.6',
        'severity': 'CRITICAL',
    },
    'exit_count': {
        'name': 'Minimum Number of Exits',
        'description': 'Minimum 2 exits per floor for any area >93 m² or >50 occupants.',
        'reference': 'Chapter 10, Section 11.4',
        'severity': 'CRITICAL',
    },
    'travel_distance': {
        'name': 'Max Travel Distance to Exit',
        'description': 'Sprinklered: ≤60 m. Non-sprinklered: ≤45 m from any point to nearest exit.',
        'reference': 'Chapter 10, Section 11.4 – Table 3.6A',
        'severity': 'CRITICAL',
    },
    'corridor_width': {
        'name': 'Minimum Corridor Width',
        'description': '≥1200 mm clear width for any corridor serving 50 or more occupants.',
        'reference': 'Chapter 10, Section 11.6.5 – Table 3.6B',
        'severity': 'CRITICAL',
    },
    'sprinkler_system': {
        'name': 'Sprinkler System Installation',
        'description': 'Mandatory in all buildings ≥3 floors or ≥14 m height.',
        'reference': 'Chapter 9, Section 25 – Fire Protection Systems',
        'severity': 'CRITICAL',
    },
    'smoke_detector': {
        'name': 'Smoke Detector Coverage',
        'description': 'Maximum 60 m² coverage per detector. Max 7.5 m spacing.',
        'reference': 'Chapter 9, Section 17 – Fire Detection',
        'severity': 'HIGH',
    },
    'fire_extinguisher': {
        'name': 'Fire Extinguisher Placement',
        'description': 'Maximum 25 m travel distance. Minimum one per 200 m².',
        'reference': 'Chapter 9, Section 13 – Portable Fire Extinguishers',
        'severity': 'HIGH',
    },
    'fire_truck_access': {
        'name': 'Fire Truck Access Road',
        'description': 'Minimum 4 m clear road width and 4 m overhead clearance.',
        'reference': 'Chapter 3 – Site Requirements, Section 5',
        'severity': 'HIGH',
    },
    'exit_separation': {
        'name': 'Exit Separation Distance',
        'description': 'Sprinklered: ≥1/3 of building diagonal. Non-sprinklered: ≥1/2.',
        'reference': 'Chapter 10, Section 11.3',
        'severity': 'HIGH',
    },
    'emergency_lighting': {
        'name': 'Emergency Lighting',
        'description': 'Required in all corridors and exit routes. Min 1 lux. Battery min 1 hour.',
        'reference': 'Chapter 9, Section 23 – Emergency Lighting',
        'severity': 'MEDIUM',
    },
}
